### PR TITLE
Add code formatting files

### PR DESCRIPTION
**Pull request by peterblazejewicz**
This is optional, but I think it could be beneficial for users as project is a template.

The .prettierrc contains a rule that switch default double quotes to single
quotes (ones used in tsconfig)
The .editorconfig reflects settings used in source code - so when sample code
is used e.g. in VSCode and code is formatted a minimal change occurs compared to
original example code

Thanks!

### CODE REVIEW

**Comment by frederikprijck** [comment]
Hi @peterblazejewicz,

Thanks for the PR.

Iirc `.prettierrc` is for when you're using `prettier`, which I am not in this starter. Adding a `.prettierrc` file wouldn't make sense from that perspective.
If you do prefer to add the prettierrc file, I think we should have a prettier step in the build aswell. But my guess is, this isn't realy the scope of the repo.

I'm not sure about `.editorconfig` neither. The reason for this starter is to show you how a modern setup can look like. Adding an `.editorconfig` doesn't sound like the scope of this repo neither, as I do not think it's this repo's responsibility to force certain editor configurations.

However I do not see any harm in adding it, so if you can remove the prettierrc file, I can merge this in.
Merging in `prettierrc` would require more changes, aswell as an extra build step. Feel free if you do want to add prettier! :)

**Comment by peterblazejewicz** [comment]
@frederikprijck Sorry for a delay, was at work. 
I've rebased the PR and now it just adds configuration files into `.gitignore`. This should allow a user like me - to actively use your template 'as is', but without a need to add configuration file changes via commits.
I work with your content as we have a legacy up in NG1.* that begs for migration paths.
Thanks!

**Comment by peterblazejewicz** [comment]
ops, wait a sec - I forgot to reverse file additions.

**Comment by frederikprijck** [comment]
So if I understand this correct, you're adding these two files to the `.gitignore` because you're using them locally ?

Why should this be part of the repository? Because someone wants to ignore them doesn't mean other people can't include them in git, right ?

**Comment by peterblazejewicz** [comment]
Forget, I'm not using them in my own project. I'm using a git based project. Thanks for your time though!

**Pull request closed without merging**
